DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
    ID INT NOT NULL AUTO_INCREMENT ,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);
DROP TABLE IF EXISTS CUENTA;
CREATE TABLE CUENTA (
    ID INT NOT NULL ,
    PASSWORD VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE VERIFICACION (
   TIPO INT NOT NULL ,
   ID INT NOT NULL ,
   PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS JUGADORES;
CREATE TABLE JUGADORES (
    NOMBRE VARCHAR(255) NOT NULL,
    POSICION VARCHAR(255) NOT NULL,
    EQUIPO VARCHAR(255) NOT NULL,
    NPARTIDOS INTEGER NOT NULL,
    GOLES INTEGER NOT NULL,
    ASISTENCIAS INTEGER NOT NULL,
    AMARILLAS INTEGER NOT NULL,
    ROJAS INTEGER NOT NULL,
    PRIMARY KEY (NOMBRE)
);

DROP TABLE IF EXISTS EQUIPOS;
CREATE TABLE EQUIPOS (
    NOMBRE VARCHAR(255) NOT NULL,
    ENTRENADOR VARCHAR(255) NOT NULL,
    PRESIDENTE VARCHAR(255) NOT NULL,
    ESTADIO VARCHAR(255) NOT NULL,
    POSICION INTEGER NOT NULL,
    CAPACIDAD INTEGER NOT NULL,
    MSALARIAL INTEGER NOT NULL,
    PRIMARY KEY (NOMBRE)
);